server:
  port : 8081
spring:
  datasource:
    url: jdbc:h2:mem:mydb #jdbc:h2:file:/data/demo for persistent demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


